questions = [
    {
        "question": """What is Docker?""",
        "answer": """Docker is a platform for developing, shipping, and running applications in containers - lightweight, standalone packages that include everything needed to run an application.""",
        "topic": "docker"
    },
    {
        "question": """What is a Docker Container?""",
        "answer": """A container is a standard unit of software that packages code and all its dependencies so the application runs quickly and reliably across different computing environments.""",
        "topic": "docker"
    },
    {
        "question": """What is a Docker Image?""",
        "answer": """A Docker image is a lightweight, standalone, executable package that includes everything needed to run an application: code, runtime, system tools, libraries, and settings.""",
        "topic": "docker"
    },
    {
        "question": """What is Docker Compose?""",
        "answer": """Docker Compose is a tool for defining and running multi-container Docker applications. It uses YAML files to configure application services.""",
        "topic": "docker"
    },
    {
        "question": """What is a Dockerfile?""",
        "answer": """A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image.""",
        "topic": "docker"
    },
    {
        "question": """What is Docker Hub?""",
        "answer": """Docker Hub is a cloud-based registry service that allows you to link to code repositories, build images, store them, and test them.""",
        "topic": "docker"
    },
    {
        "question": """What is Docker Volume?""",
        "answer": """Docker volumes are the preferred mechanism for persisting data generated by and used by Docker containers.""",
        "topic": "docker"
    },
    {
        "question": """What is Docker Network?""",
        "answer": """Docker networking enables containers to communicate with each other and with the outside world. It provides complete isolation for containers.""",
        "topic": "docker"
    },
    {
        "question": """What is the difference between CMD and ENTRYPOINT in Dockerfile?""",
        "answer": """CMD provides defaults for executing container while ENTRYPOINT defines the executable that will always run when the container starts.""",
        "topic": "docker"
    },
    {
        "question": """What is Docker Swarm?""",
        "answer": """Docker Swarm is a native clustering and orchestration solution for Docker. It turns a pool of Docker hosts into a single, virtual Docker host.""",
        "topic": "docker"
    },
]
