name: Deploy and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
  
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Wait for deployment
      #   run: sleep 30  # Wait for deployment to complete

      # - name: Run post-deployment tests
      #   env:
      #     BASE_URL: ${{ steps.deploy.outputs.url }}
      #   run: |
      #     python -m pytest tests/test_deployment.py

      # - name: Check website status
      #   run: |
      #     response=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.BASE_URL }})
      #     if [ $response -eq 200 ]; then
      #       echo "Website is up and running!"
      #     else
      #       echo "Website check failed with status code: $response"
      #       exit 1
      #     fi 